"use client";

import "./globals.css";
import { getLibrary } from "@/config/web3";
import { Web3ReactProvider } from "@web3-react/core";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <Web3ReactProvider getLibrary={getLibrary}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Web3ReactProvider>
  );
};

export default RootLayout;
